raw_data_dir: data
dataset_name: sample
base_features:
  - feature: passenger_id
    dtype: INT32

  - feature: sibsp
    dtype: INT32

  - feature: parch
    dtype: INT32

  - feature: fare
    dtype: FLOAT

  - feature: age
    dtype: FLOAT


transforming_features:
  - feature: is_train
    index: 1
    dependencies:
     - passenger_id
    dtype: BOOL

  - feature: imputed_age
    index: 2
    dtype: FLOAT
    dependencies:
      - age
      - is_train

  - feature: bucketized_age
    index: 3
    dtype: FLOAT
    dependencies:
      - imputed_age

  - feature: survived
    index: 5
    dtype: FLOAT

  - index: 6
    feature: sex
    dtype: STRING

  - feature: coded_sex
    index: 7
    dependencies:
      - sex
    dtype: INT32

  - feature: pclass
    index: 8
    dtype: FLOAT

  - feature: coded_pclass
    index: 9
    dependencies:
      - pclass
    dtype: INT32

  - feature: embarked
    index: 10
    dtype: STRING

  - feature: coded_embarked
    index: 11
    dtype: INT32
    dependencies:
      - embarked

  - feature: title
    index: 12
    dtype: STRING

  - feature: coded_title
    index: 13
    dtype: INT32
    dependencies:
      - title

  - feature: min_max_scaled_age
    index: 14
    dtype: FLOAT
    dependencies:
      - imputed_age
      - is_train
