config_name: "lgbm"

data_loader:
  cls_name: tabml.data_loaders.BaseDataLoader
  feature_config_path: configs/feature_config.yaml

  features_to_model:
    - coded_sex
    - imputed_age
    - bucketized_age
    - min_max_scaled_age
    - coded_pclass
    - coded_title

  label_col: survived

  train_filters:
    - PassengerId <= 891

  validation_filters:
    - not is_train
    - PassengerId <= 891

model_wrapper:
  cls_name: tabml.model_wrappers.LgbmClassifierModelWrapper
  model_params:
    learning_rate: 0.01
  fit_params:
    categorical_feature:
      - coded_sex
      - coded_pclass
      - coded_title

model_analysis:
  training_size: 100
  metrics:
    - accuracy_score
    - roc_auc
    - max_f1
  by_features:
    - Sex
    - Pclass
