# This config use RandomForest as an example of using a scikit learn model in
# TabML. Sklearn RandomForest does not handle categorical features directly.
config_name: "tabnet"

data_loader:
  cls_name: tabml.data_loaders.BaseDataLoader
  feature_config_path: configs/feature_config.yaml

  features_to_model:
    - coded_sex
    - coded_pclass
    - coded_title
    - imputed_age
    - bucketized_age
    - min_max_scaled_age

  label_col: survived

  train_filters:
    - passenger_id <= 891
    - is_train

  validation_filters:
    - passenger_id <= 891
    - not is_train

model_wrapper:
  cls_name: tabml.model_wrappers.TabNetClassifierModelWrapper
  model_params:
    n_d: 8
    n_a: 8
    cat_features:
      - feature: "coded_sex"
        dim: 2
        emb_dim: 1

      - feature: "coded_pclass"
        dim: 3
        emb_dim: 2

      - feature: "coded_title"
        dim: 6
        emb_dim: 3

model_analysis:
  training_size: 100
  metrics:
    - accuracy_score
    - roc_auc
    - max_f1
  by_features:
    - sex
    - pclass
