ignore:
  - "setup.py"

codecov:
  disable_default_path_fixes: false

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
       # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
