raw_data_dir: "data"
dataset_name: "processed"

base_features:
  - name: "house_id"
    dtype: int32
  - name: "median_house_value"
    dtype: float32
  - name: "housing_median_age"
    dtype: float32
  - name: "total_rooms"
    dtype: float32
  - name: "population"
    dtype: float32
  - name: "total_bedrooms"
    dtype: float32
  - name: "households"
    dtype: float32
  - name: "median_income"
    dtype: float32
  - name: "ocean_proximity"
    dtype: str
  - name: "longitude"
    dtype: float32
  - name: "latitude"
    dtype: float32

transforming_features:
  - name: "is_train"
    index: 1
    dtype: bool
    dependencies:
      - "house_id"

  - name: "scaled_housing_median_age"
    index: 2
    dtype: float32
    dependencies:
      - "is_train"
      - "housing_median_age"
  - name: "scaled_total_rooms"
    index: 3
    dtype: float32
    dependencies:
      - "is_train"
      - "total_rooms"
  - name: "scaled_population"
    index: 4
    dtype: float32
    dependencies:
      - "is_train"
      - "population"
  - name: "scaled_total_bedrooms"
    index: 5
    dtype: float32
    dependencies:
      - "is_train"
      - "total_bedrooms"

  - name: "scaled_households"
    index: 6
    dtype: float32
    dependencies:
      -  "is_train"
      - "households"

  - name: "scaled_median_income"
    index: 7
    dtype: float32
    dependencies:
      - "is_train"
      - "median_income"

  - name: "log10_median_house_value"
    dtype: float32
    index: 8
    dependencies:
      - "median_house_value"

  - name: "bucketized_longitude"
    index: 9
    dtype: int32
    dependencies:
      -  "longitude"

  - name: "bucketized_latitude"
    index: 10
    dtype: int32
    dependencies:
      - "latitude"
  - name: "bucketized_latitude_X_bucketized_longitude"
    index: 11
    dtype: str
    dependencies:
      -  "bucketized_latitude"
      - "bucketized_longitude"

  - name: "hashed_bucketized_latitude_X_bucketized_longitude"
    index: 12
    dtype: int32
    dependencies:
      - "bucketized_latitude_X_bucketized_longitude"

  - name: "encoded_ocean_proximity"
    index:  13
    dtype: int32
    dependencies:
      - "ocean_proximity"
