raw_data_dir: data
dataset_name: sample
base_features:
  - name: PassengerId
    dtype: INT32

  - name: SibSp
    dtype: INT32

  - name: Parch
    dtype: INT32

  - name: Fare
    dtype: FLOAT

  - name: Age
    dtype: FLOAT

  - name: Sex
    dtype: STRING

  - name: Pclass
    dtype: FLOAT

  - name: Embarked
    dtype: STRING

  - name: Name
    dtype: STRING

transforming_features:
  - name: is_train
    dependencies:
      - PassengerId
    dtype: BOOL

  - name: imputed_age
    dtype: FLOAT
    dependencies:
      - Age
      - is_train

  - name: bucketized_age
    # dtype: FLOAT
    output_features:
      - name: bucketized_age_v1
        dtype: FLOAT
      - name: bucketized_age_v2
        dtype: FLOAT
    dependencies:
      - imputed_age

  - name: survived
    dtype: FLOAT

  - name: coded_sex
    dependencies:
      - Sex
    dtype: INT32

  - name: coded_pclass
    dtype: INT32
    dependencies:
      - Pclass
  - name: imputed_embarked
    dtype: STRING
    dependencies:
      - Embarked

  - name: coded_embarked
    dtype: INT32
    dependencies:
      - imputed_embarked

  - name: title
    dtype: STRING
    dependencies:
      - Name

  - name: coded_title
    dtype: INT32
    dependencies:
      - title

  - name: min_max_scaled_age
    dtype: FLOAT
    dependencies:
      - imputed_age
      - is_train
