raw_data_dir: data
dataset_name: processed

base_features:
  - name: house_id
    dtype: INT32
  - name: median_house_value
    dtype: FLOAT
  - name: housing_median_age
    dtype: FLOAT
  - name: total_rooms
    dtype: FLOAT
  - name: population
    dtype: FLOAT
  - name: total_bedrooms
    dtype: FLOAT
  - name: households
    dtype: FLOAT
  - name: median_income
    dtype: FLOAT
  - name: ocean_proximity
    dtype: STRING
  - name: longitude
    dtype: FLOAT
  - name: latitude
    dtype: FLOAT

transforming_features:
  - name: is_train
    dtype: BOOL
    dependencies:
      - house_id

  - name: scaled_housing_median_age
    dtype: FLOAT
    dependencies:
      - is_train
      - housing_median_age
  - name: scaled_total_rooms
    dtype: FLOAT
    dependencies:
      - is_train
      - total_rooms
  - name: scaled_population
    dtype: FLOAT
    dependencies:
      - is_train
      - population
  - name: scaled_total_bedrooms
    dtype: FLOAT
    dependencies:
      - is_train
      - total_bedrooms

  - name: scaled_households
    dtype: FLOAT
    dependencies:
      - is_train
      - households

  - name: scaled_median_income
    dtype: FLOAT
    dependencies:
      - is_train
      - median_income

  - name: log10_median_house_value
    dtype: FLOAT
    dependencies:
      - median_house_value

  - name: bucketized_longitude
    dtype: INT32
    dependencies:
      - longitude

  - name: bucketized_latitude
    dtype: INT32
    dependencies:
      - latitude

  - name: hashed_bucketized_latitude_X_bucketized_longitude
    dtype: INT32
    dependencies:
      - bucketized_latitude
      - bucketized_longitude

  - name: encoded_ocean_proximity
    dtype: INT32
    dependencies:
      - ocean_proximity

prediction_features:
  - name: pred_lgbm
    dtype: FLOAT
