config_name: stacking
data_loader:
    cls_name: tabml.data_loaders.BaseDataLoader
    feature_config_path: configs/feature_config.yaml

    features_to_model:
      - pred_lgbm
      - pred_catboost
      - pred_xgbost

    label_col: median_house_value

    # TODO: change filters in all configs.
    train_filters: [is_train]

    validation_filters: [not is_train]

    submission_filters: [not is_train]

model_wrapper:
    cls_name: tabml.model_wrappers.BaseSklearnModelWrapper
    sklearn_cls: sklearn.linear_model.LinearRegression

model_analysis:
    metrics: [smape, rmse, r2]
    by_features: [ocean_proximity]
    training_size: 500
