# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tabml/protos/model_wrappers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tabml/protos/model_wrappers.proto',
  package='tabml.protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!tabml/protos/model_wrappers.proto\x12\x0ctabml.protos\"\xcb\x03\n\x16ModelWrapperLgbmParams\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\x12\x14\n\x0cn_estimators\x18\x02 \x01(\x05\x12\x12\n\nnum_leaves\x18\x03 \x01(\x05\x12\x11\n\tmax_depth\x18\x04 \x01(\x05\x12\x1d\n\tobjective\x18\x05 \x01(\t:\nregression\x12\x18\n\x10\x63olsample_bytree\x18\x06 \x01(\x02\x12\x11\n\tsubsample\x18\x07 \x01(\x02\x12\x11\n\treg_alpha\x18\x08 \x01(\x02\x12\x16\n\x0emin_split_gain\x18\t \x01(\x02\x12\x12\n\nreg_lambda\x18\n \x01(\x02\x12\x18\n\x10min_child_weight\x18\x0b \x01(\x02\x12\x19\n\x11min_child_samples\x18\x0c \x01(\x05\x12\x18\n\x0crandom_state\x18\r \x01(\x05:\x02\x34\x32\x12\x16\n\x0esubsample_freq\x18\x0e \x01(\x05\x12\x19\n\x11subsample_for_bin\x18\x0f \x01(\x05\x12\x15\n\rboosting_type\x18\x10 \x01(\t\x12\x0e\n\x06metric\x18\x11 \x01(\t\x12\x18\n\x10scale_pos_weight\x18\x12 \x01(\x05\x12\x0f\n\x07max_bin\x18\x13 \x01(\x05\"\xa0\x02\n\x19ModelWrapperXgboostParams\x12\x0f\n\x07use_gpu\x18\x01 \x01(\x08\x12\x11\n\tmax_depth\x18\x02 \x01(\x05\x12\x14\n\x0cn_estimators\x18\x03 \x01(\x05\x12\r\n\x05gamma\x18\x04 \x01(\x02\x12#\n\tobjective\x18\x05 \x01(\t:\x10reg:squarederror\x12\x18\n\x10\x63olsample_bytree\x18\x06 \x01(\x02\x12\x11\n\tsubsample\x18\x07 \x01(\x02\x12\x11\n\treg_alpha\x18\x08 \x01(\x02\x12\x12\n\nreg_lambda\x18\t \x01(\x02\x12\x15\n\rlearning_rate\x18\n \x01(\x02\x12\x18\n\x10min_child_weight\x18\x0b \x01(\x02\x12\x10\n\x04seed\x18\x0c \x01(\x05:\x02\x34\x32\"\xaa\x01\n\x0cModelWrapper\x12\x10\n\x08\x63ls_name\x18\x01 \x02(\t\x12;\n\x0blgbm_params\x18\x02 \x01(\x0b\x32$.tabml.protos.ModelWrapperLgbmParamsH\x00\x12\x41\n\x0exgboost_params\x18\x03 \x01(\x0b\x32\'.tabml.protos.ModelWrapperXgboostParamsH\x00\x42\x08\n\x06params'
)




_MODELWRAPPERLGBMPARAMS = _descriptor.Descriptor(
  name='ModelWrapperLgbmParams',
  full_name='tabml.protos.ModelWrapperLgbmParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='tabml.protos.ModelWrapperLgbmParams.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_estimators', full_name='tabml.protos.ModelWrapperLgbmParams.n_estimators', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_leaves', full_name='tabml.protos.ModelWrapperLgbmParams.num_leaves', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_depth', full_name='tabml.protos.ModelWrapperLgbmParams.max_depth', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objective', full_name='tabml.protos.ModelWrapperLgbmParams.objective', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"regression".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colsample_bytree', full_name='tabml.protos.ModelWrapperLgbmParams.colsample_bytree', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subsample', full_name='tabml.protos.ModelWrapperLgbmParams.subsample', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_alpha', full_name='tabml.protos.ModelWrapperLgbmParams.reg_alpha', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_split_gain', full_name='tabml.protos.ModelWrapperLgbmParams.min_split_gain', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_lambda', full_name='tabml.protos.ModelWrapperLgbmParams.reg_lambda', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_child_weight', full_name='tabml.protos.ModelWrapperLgbmParams.min_child_weight', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_child_samples', full_name='tabml.protos.ModelWrapperLgbmParams.min_child_samples', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='random_state', full_name='tabml.protos.ModelWrapperLgbmParams.random_state', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=42,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subsample_freq', full_name='tabml.protos.ModelWrapperLgbmParams.subsample_freq', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subsample_for_bin', full_name='tabml.protos.ModelWrapperLgbmParams.subsample_for_bin', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boosting_type', full_name='tabml.protos.ModelWrapperLgbmParams.boosting_type', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metric', full_name='tabml.protos.ModelWrapperLgbmParams.metric', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale_pos_weight', full_name='tabml.protos.ModelWrapperLgbmParams.scale_pos_weight', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_bin', full_name='tabml.protos.ModelWrapperLgbmParams.max_bin', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=511,
)


_MODELWRAPPERXGBOOSTPARAMS = _descriptor.Descriptor(
  name='ModelWrapperXgboostParams',
  full_name='tabml.protos.ModelWrapperXgboostParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_gpu', full_name='tabml.protos.ModelWrapperXgboostParams.use_gpu', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_depth', full_name='tabml.protos.ModelWrapperXgboostParams.max_depth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_estimators', full_name='tabml.protos.ModelWrapperXgboostParams.n_estimators', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='tabml.protos.ModelWrapperXgboostParams.gamma', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objective', full_name='tabml.protos.ModelWrapperXgboostParams.objective', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"reg:squarederror".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colsample_bytree', full_name='tabml.protos.ModelWrapperXgboostParams.colsample_bytree', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subsample', full_name='tabml.protos.ModelWrapperXgboostParams.subsample', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_alpha', full_name='tabml.protos.ModelWrapperXgboostParams.reg_alpha', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_lambda', full_name='tabml.protos.ModelWrapperXgboostParams.reg_lambda', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='tabml.protos.ModelWrapperXgboostParams.learning_rate', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_child_weight', full_name='tabml.protos.ModelWrapperXgboostParams.min_child_weight', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seed', full_name='tabml.protos.ModelWrapperXgboostParams.seed', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=42,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=802,
)


_MODELWRAPPER = _descriptor.Descriptor(
  name='ModelWrapper',
  full_name='tabml.protos.ModelWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cls_name', full_name='tabml.protos.ModelWrapper.cls_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lgbm_params', full_name='tabml.protos.ModelWrapper.lgbm_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xgboost_params', full_name='tabml.protos.ModelWrapper.xgboost_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='params', full_name='tabml.protos.ModelWrapper.params',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=805,
  serialized_end=975,
)

_MODELWRAPPER.fields_by_name['lgbm_params'].message_type = _MODELWRAPPERLGBMPARAMS
_MODELWRAPPER.fields_by_name['xgboost_params'].message_type = _MODELWRAPPERXGBOOSTPARAMS
_MODELWRAPPER.oneofs_by_name['params'].fields.append(
  _MODELWRAPPER.fields_by_name['lgbm_params'])
_MODELWRAPPER.fields_by_name['lgbm_params'].containing_oneof = _MODELWRAPPER.oneofs_by_name['params']
_MODELWRAPPER.oneofs_by_name['params'].fields.append(
  _MODELWRAPPER.fields_by_name['xgboost_params'])
_MODELWRAPPER.fields_by_name['xgboost_params'].containing_oneof = _MODELWRAPPER.oneofs_by_name['params']
DESCRIPTOR.message_types_by_name['ModelWrapperLgbmParams'] = _MODELWRAPPERLGBMPARAMS
DESCRIPTOR.message_types_by_name['ModelWrapperXgboostParams'] = _MODELWRAPPERXGBOOSTPARAMS
DESCRIPTOR.message_types_by_name['ModelWrapper'] = _MODELWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelWrapperLgbmParams = _reflection.GeneratedProtocolMessageType('ModelWrapperLgbmParams', (_message.Message,), {
  'DESCRIPTOR' : _MODELWRAPPERLGBMPARAMS,
  '__module__' : 'tabml.protos.model_wrappers_pb2'
  # @@protoc_insertion_point(class_scope:tabml.protos.ModelWrapperLgbmParams)
  })
_sym_db.RegisterMessage(ModelWrapperLgbmParams)

ModelWrapperXgboostParams = _reflection.GeneratedProtocolMessageType('ModelWrapperXgboostParams', (_message.Message,), {
  'DESCRIPTOR' : _MODELWRAPPERXGBOOSTPARAMS,
  '__module__' : 'tabml.protos.model_wrappers_pb2'
  # @@protoc_insertion_point(class_scope:tabml.protos.ModelWrapperXgboostParams)
  })
_sym_db.RegisterMessage(ModelWrapperXgboostParams)

ModelWrapper = _reflection.GeneratedProtocolMessageType('ModelWrapper', (_message.Message,), {
  'DESCRIPTOR' : _MODELWRAPPER,
  '__module__' : 'tabml.protos.model_wrappers_pb2'
  # @@protoc_insertion_point(class_scope:tabml.protos.ModelWrapper)
  })
_sym_db.RegisterMessage(ModelWrapper)


# @@protoc_insertion_point(module_scope)
