# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master, dev]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Install tabml
      run: |
        python setup.py install
    - name: Lint with flake8, tpye check with mypy
      run: |
        flake8 ./tabml
        mypy --show-traceback ./tabml # see configs in /mypy.ini
    - name: Test with pytest
      run: |
        # python3 -m pytest -s --durations=0 . # https://stackoverflow.com/a/55095253
        python3 -m pytest -s --durations=0 --cov=./ --cov-report=xml tabml/
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        directory: ./coverage/reports/
        flags: pytest
        env_vars: OS,PYTHON
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
